### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by vivarose** [manoharan-lab/flyvbjerg-std-err#1]
Hi!

I am getting a lot of IndexError problems when I use this code.

For example, in the code

``` python

def random_walk(N):
    return np.cumsum(np.random.randn(N))

no_error_count = 0
IndexError_count = 0

for i in range(10000):
    try:
        fp_stderr(random_walk(100))
        no_error_count += 1
    except IndexError:
        IndexError_count += 1
        pass
```

I will get a no_error_count of 1674 and an IndexError_count of 8326. Getting an error 83% of the time!
I'm cheating a little above because I'm feeding a random walk directly to fp_stderr, which is not my normal usage. In my experimental data, I get an error about 40% of the time. This is smaller than the sample code above but nevertheless quite inconvenient.

**Comment by vivarose** [comment]
I should probably provide the error message:

``` python
def corr_data(N, L):
    '''Generate random correlated data containing 2^N data points.
    Randon data is convolved over a 2^L/10 length to give the correlated signal.'''
    return np.convolve(np.random.randn(2**N), np.ones(2**L)/10, 'same')

data = corr_data(3,3)
print data
fp_stderr(data)
```

gives me the following:

```
[-0.1628192  -0.1020165  -0.07506157  0.09565024  0.10744972  0.24835386
  0.28898498  0.26281557]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-181-7c006661bd5e> in <module>()
      1 data = corr_data(3,3)
      2 print data
----> 3 fp_stderr(data)

/home/viva/code/flyvbjerg-std-err/flyvbjerg_petersen_std_err.pyc in fp_stderr(data)
    191     block_trans_var, block_trans_sev = calculate_blocked_variances(data)
    192     var_mean, conv, bounds = detect_fixed_point(block_trans_var,
--> 193                                                 block_trans_sev, True)
    194 
    195     if not conv:

/home/viva/code/flyvbjerg-std-err/flyvbjerg_petersen_std_err.pyc in detect_fixed_point(fp_var, fp_sev, full_output)
    137     for i in np.arange(n_trans):
    138         # ith point inside error bars of next point
--> 139         if np.abs(fp_var[i + 1] - fp_var[i]) < fp_var[i + 1] * fp_sev[i + 1]:
    140             left_index = i
    141             break

IndexError: index 1 is out of bounds for axis 0 with size 1
```

**Comment by RebeccaWPerry** [comment]
I can't look at it now, but in an effort to offer help in case you are in a
rush: flyvbjerg-std-err is meant to be used with very long data sets
(~10,000 steps). Could you please see if the error goes away when you use
longer data sets?

**Comment by vivarose** [comment]
![image](https://cloud.githubusercontent.com/assets/8671269/13974906/83741e2c-f086-11e5-9be5-d7cb28abf586.png)
Yes, it generally works with longer data-sets. Here I am comparing this package to the results from the [pyblock](http://pyblock.readthedocs.org/en/latest/#) package. I generated random correlated data of lengths ranging from 2^4 to 2^20 and for each dataset, I calculated the stderr using each package on the same dataset, then plotted the results. I ran it a few times and selected this plot because it showed one datapoint missing from the pf_stderr, indicating one case of an IndexError, whereas pyblock has three missing datapoints.

**Comment by jeromefung** [comment]
I'm looking at this code now for the first time in a long time and can
reproduce the IndexErrors you're getting.

From my poking around it's pretty clear that with the very short data sets
you're using (e.g. a 100-step random walk) the block decorrelation does not
converge to a fixed point. Since with such a short random walk, only a
handful of correlation steps are possible, this is not surprising. The
algorithm looks fine, but I would agree that the code is not failing in a
nice way.

I can try to patch this, perhaps in the next week or so, but I don't want
to throw something up that is going to make things worse.

J

**Comment by jeromefung** [comment]
Wait a minute... there's something unusual about trying to calculate the
standard error of the mean for a time series that is a random walk. The
particle positions in a random walk are highly correlated, so it's not
surprising that you can't _decorrelate_ them. This doesn't change the fact
that the code is not failing in a nice way, but the test case seems like an
odd one. Originally I had written the code to work with squared
displacements from a random walk, not the random walk trajectory itself.

FWIW, if I run the snippet above but with the function

def random_walk_sq_disps(N):
    return np.random.randn(N)**2

instead of random_walk, I get no_error_count = 9974 and IndexError_count =
26 -- a much more reasonable success rate.

J

**Comment by vivarose** [comment]
I agree that using a random walk is an odd choice. My second post has a different way of generating correlated data, and that approach didn't generate as many IndexErrors. The real measure is how it behaves with my experimental data, which was, I guess, too full of short trajectories.

Now that I understand that this is a fundamental limit to estimating a stderr rather than some problem with the code, I think I'll just close the Issue I opened.

Anyway, at the point I have set up [my code](https://github.com/vivarose/trackpy/blob/using_fp_stderr/trackpy/motion.py) to handle the IndexError, so I am no longer inconvenienced by the way your code operates. In fact, if you change your code, I will have to change mine!

**Comment by vivarose** [comment]
Question: If my movie is too short but I have lots of particles, could I calculate the square displacements for each particle, then concatenate the square displacements together and feed that into fp_stderr to get an error estimate for the ensemble mean square displacement?

**Comment by jeromefung** [comment]
I think that works (at least to first approximation), but I'm also pretty
sure there's a smarter way to deal with this particularly if your
trajectories vary in length. Some of the papers by Thierry Savin and
Patrick Doyle may have addressed the specific issue of correctly weighting
trajectories of different lengths, if I recall correctly.

Jerome
